apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    course: OPS300
spec:
  type: ClusterIP
  selector:
    course: OPS300
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
